name: 'Lint/Build/Test'
description: 'lint, format, typecheck, build'

inputs:
  skip-build:
    description: 'Skip the build step'
    required: false
    default: 'false'
  skip-test:
    description: 'Skip the test step'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: '🧹 Lint'
      shell: bash
      run: |
        pnpm lint
        # https://github.com/oxc-project/oxc
        pnpmx dlx oxlint@latest . --fix --import-plugin --ignore-pattern="dist"

    - name: '🧹 Format'
      shell: bash
      run: pnpm format

    - name: '🧪 Typecheck'
      shell: bash
      run: pnpm typecheck

    - name: '🔧 Build'
      shell: bash
      run: pnpm run build

    - name: '🧪 Test'
      shell: bash
      run: pnpm test
