name: Checks

permissions:
  contents: 'write'

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # if you want to cancel runs when a new one is queued, set this to true
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-checks]') }}
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: '🧹 Lint'
        shell: bash
        run: pnpm lint

      - name: '🧹 Format'
        shell: bash
        run: pnpm format

      - name: '🧪 Typecheck'
        shell: bash
        run: pnpm check:types

      - name: '🔧 Build'
        shell: bash
        run: pnpm run build

      - name: '🧪 Test'
        shell: bash
        run: pnpm test
