name: CI

permissions:
  contents: 'write'

on:
  pull_request:
  push:
    branches:
      # not 'main' branch
      - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  CI: true
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  CI:
    name: 'Lint & Format & Test'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node_version: ['lts/*']
        pnpm_version: ['latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ matrix.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: |
          pnpm format
          pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
