name: Publish Package

permissions:
  contents: 'read'
  packages: 'write'
  id-token: 'write'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # if you want to cancel runs when a new one is queued, set this to true
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-deploy]') }}
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: '📦 Install Dependencies'
        uses: ./.github/actions/install-dependencies
        with:
          frozen-lockfile: true
          registry-url: 'https://registry.npmjs.org'

      - name: '🧹 Format'
        shell: bash
        run: pnpm oxfmt --config='oxfmt.config.ts' --check

      - name: '🧹 Lint'
        shell: bash
        run: pnpm oxlint --config='oxlint.config.ts' --max-warnings=0 --format='github' --report-unused-disable-directives

      - name: '🧪 Typecheck'
        shell: bash
        run: pnpm tsgo --project 'tsconfig.json' --noEmit

      - name: '🔧 Build'
        shell: bash
        run: pnpm tsdown --config='tsdown.config.ts'

      - name: '🧪 Test'
        shell: bash
        run: pnpm vitest --run --reporter='github-actions'

      - name: 'Check Package Structure'
        run: |
          pnpm check-package

  publish-npm:
    name: 'Publish Package to npm Registry'
    needs: [checks]
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: '📦 Install Dependencies'
        uses: ./.github/actions/install-dependencies
        with:
          frozen-lockfile: true
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: pnpm tsdown --config='tsdown.config.ts'

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # https://docs.npmjs.com/generating-provenance-statements
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --access public --registry https://registry.npmjs.org --no-git-checks

  publish-gpr:
    name: 'Publish Package to GitHub Package Registry'
    needs: [checks]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: '📦 Install Dependencies'
        uses: ./.github/actions/install-dependencies
        with:
          frozen-lockfile: true
          registry-url: 'https://npm.pkg.github.com'

      - name: Build
        run: pnpm tsdown --config='tsdown.config.ts'

      - name: Update ~/.npmrc
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://docs.npmjs.com/generating-provenance-statements
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks

  # Generate GitHub Release Changelog
  Changelog:
    needs: [checks, publish-npm]
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx changelogen@latest
